name: Windows - RDP Access

on:
  workflow_dispatch:

jobs:
  rdp:
    name: Start RDP Session
    runs-on: windows-latest

    steps:
      - name: Set up Ngrok and RDP
        run: |
          # Set RDP password
          net user runneradmin "YourSecurePassword123"
          
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          
          # Enable firewall rules
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Download and unzip Ngrok
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE
          
          # Add Ngrok to PATH (for current session)
          $env:Path += ";$env:USERPROFILE"
          
          # Set Ngrok authtoken (REPLACE THIS VALUE!)
          & "$env:USERPROFILE\ngrok.exe" authtoken YOUR_NGROK_AUTHTOKEN_HERE
          
          # Start Ngrok tunnel in background
          Start-Process "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow

          Start-Sleep -Seconds 10
          
          # Fetch tunnel info
          $tunnel = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $public_url = $tunnel.tunnels.public_url
          Write-Host "🔗 RDP URL: $public_url"
          Write-Host "👤 Username: runneradmin"
          Write-Host "🔒 Password: YourSecurePassword123"

      - name: Keep Runner Alive (1 Hour)
        run: |
          for ($i = 0; $i -lt 3600; $i++) {
            Write-Host "⏳ $i seconds elapsed. Waiting for RDP connection..."
            Start-Sleep -Seconds 1
          }
