name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building ..
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Downloads.bat
        run: cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
